# Usar a imagem do PHP com as extensões necessárias para Laravel
FROM php:8.2-fpm

# Instalar dependências do sistema e o Composer
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Definir o diretório de trabalho
WORKDIR /var/www

# Copiar o código da aplicação para o contêiner
COPY . .

# Instalar dependências PHP do Composer
RUN composer install --no-dev --optimize-autoloader

# Expor a porta 8000 para o PHP-FPM
EXPOSE 8000

# Iniciar o servidor PHP-FPM
CMD ["php-fpm"]
